services:
  cooking:
    container_name: cooking
    build: .
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cooking.rule=Host(`recipes.whitney.rip`)"
      - "traefik.http.routers.cooking.entrypoints=websecure"
      - "traefik.http.routers.cooking.tls.certresolver=letsencrypt"
      - "traefik.http.services.cooking.loadbalancer.server.port=3000"

networks:
  traefik:
    external: true
